apiVersion: v1
kind: Template
metadata:
  name: frontend-base
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: insights-navigation
  spec:
    id: rhel
    title: Red Hat Insights
    appList:
    - dashboard
    - compliance
    - inventory
    - advisor
    - policies
    - ros
    - remediations
    - patch
    - tasks
    - malware
    - provisioning
    - image-builder
    - vulnerability
    - malware
    - drift
    - registration
    - trust
    - apiDocs
    - subscription-inventory
    - subscriptions  # this should be moved into groupId 'business' eventually, pending RHCLOUD-19211
    - manifests
    - policies
    - edge
    - rhsm
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: application-services-navigation
  spec:
    id: application-services
    title: Application and Data Services
    appList:
      - subscriptions  # this should be moved into groupId 'business' eventually, pending RHCLOUD-19211
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: openshift-navigation
  spec:
    id: openshift
    title: OpenShift
    appList:
      - subscriptions  # this should be moved into groupId 'business' eventually, pending RHCLOUD-19211
      - cost-management
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: ansible-navigation
  spec:
    id: ansible
    title: Ansible Automation Platform
    appList:
      - tower-analytics
      - automation-hub
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: landing-navigation
  spec:
    id: landing-navigation
    envName: ${ENV_NAME}
    customNav:
    - expandable: true
      routes:
      - appId: dashboard
        href: /insights/dashboard
        title: Red Hat Insights
      title: Red Hat Enterprise Linux
    - appId: ansible
      title: "Ansible Automation Platform"
      href: "/ansible/ansible-dashboard"

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: settings-navigation
  spec:
    id: settings
    envName: ${ENV_NAME}
    title: Settings
    appList:
    - rbac
    - notifications
    - sources
    - content-sources

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: hac-navigation
  spec:
    id: hac
    title: HAC
    appList:
      - hac-core
      - hac-dev
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: chrome
  spec:
    envName: ${ENV_NAME}
    title: Chrome
    deploymentRepo: http://test
    API:
      versions:
      - v1
    frontend:
      paths:
      - /
      - /config/chrome
    image: ${CHROME_IMAGE}
    module:
      manifestLocation: "/apps/chrome/js/fed-mods.json"
      config:
        ssoUrl: ${SSO_URL}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: landing
  spec:
    envName: ${ENV_NAME}
    title: landing
    deploymentRepo: http://test
    API:
      versions:
      - v1
    frontend:
      paths:
      - /apps/landing
    image: ${LANDING_IMAGE}
    navItems:
    - appId: landing
      title: Red Hat Enterprise Linux
      href: /
      product: "Red Hat Enterprise Linux"
    module:
      manifestLocation: "/apps/landing/fed-mods.json"
      modules:
      - id: "landing"
        module: "./RootApp"
        routes:
        - pathname: /
          exact: true

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: dashboard
  spec:
    envName: ${ENV_NAME}
    deploymentRepo: https://github.com/RedHatInsights/insights-dashboard
    title: Dashboard
    image: ${DASHBOARD_IMAGE}
    API:
      versions:
        - v1
    frontend:
      paths:
        - /apps/dashboard
    module:
      manifestLocation: "/apps/dashboard/fed-mods.json"
      modules:
      - id: "dashboard"
        module: "./RootApp"
        routes:
        - pathname: /insights/dashboard

parameters:
- name: ENV_NAME
  required: true
- name: CHROME_IMAGE
  value: quay.io/cloudservices/insights-chrome-frontend:8e42613
- name: LANDING_IMAGE
  value: quay.io/cloudservices/landing-page-frontend:0339bc8
- name: DASHBOARD_IMAGE
  value: quay.io/cloudservices/insights-dashboard-frontend:413c94a
- name: SSO_URL
  value: https://
