apiVersion: v1
kind: Template
metadata:
  name: frontend-base
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: insights-navigation
  spec:
    id: rhel
    title: RHEL
    appList:
    - inventory
    - advisor
    - policies
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: landing-navigation
  spec:
    id: landing-navigation
    envName: ${ENV_NAME}
  customNav:
    - id: rhel
      appId: dashboard
      title: Red Hat Enterprise Linux
      href: /insights/inventory

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: settings-navigation
  spec:
    id: settings
    envName: ${ENV_NAME}
    title: Settings
    appList:
    - rbac
    - notifications
    - sources

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Bundle
  metadata:
    name: hac-navigation
  spec:
    id: hac
    title: HAC
    appList:
      - hac-core
    envName: ${ENV_NAME}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: chrome
  spec:
    envName: ${ENV_NAME}
    title: Chrome
    deploymentRepo: http://test
    API:
      versions:
      - v1
    frontend:
      paths:
      - /
      - /config/chrome
    image: ${CHROME_IMAGE}

- apiVersion: cloud.redhat.com/v1alpha1
  kind: Frontend
  metadata:
    name: landing
  spec:
    envName: ${ENV_NAME}
    title: landing
    deploymentRepo: http://test
    API:
      versions:
      - v1
    frontend:
      paths:
      - /apps/landing
    image: ${LANDING_IMAGE}
    extensions:
    - type: "cloud.redhat.com/frontend"
      properties:
        module:
          manifestLocation: "/apps/landing/fed-mods.json"
          modules:
          - id: "landing"
            module: "./RootApp"
            routes:
            - pathname: /
              exact: true

parameters:
- name: ENV_NAME
  required: true
- name: CHROME_IMAGE
  value: quay.io/cloudservices/insights-chrome-frontend:0b89c37
- name: LANDING_IMAGE
  value: quay.io/redhat-cloud-services/landing:3b067f63f54c7a9edd3c3e13156ec8aaa123a0c94
